version: '3.8'

services:
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: ../..
      dockerfile: Dockerfile.api
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - ../..:/app

volumes:
  mongo-data:
